image_width: 1280
image_height: 720
camera_name: head_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1097.90493,     0.     ,   605.21067,
             0.     ,  1098.37724,   354.45548,
             0.     ,     0.     ,     1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.071966, -0.089777, 0.000967, -0.005424, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1113.33264,     0.     ,   598.82185,     0.     ,
             0.     ,  1120.65125,   355.09151,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
