#!/bin/sh
#
# @name Solo
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MC_PITCHRATE_P 0.1
param set-default MC_ROLLRATE_P 0.05

# following params added by spx to begin gimbal
param set-default TRIG_INTERFACE 3
param set-default TRIG_MODE 4
param set-default MNT_MODE_IN 4
param set-default MNT_MODE_OUT 2
param set-default MAV_PROTO_VER 2

set MIXER quad_x
